customhost = "employee.c2rungvt7r1c.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "footunhoymarcus-employee"
customregion = "us-east-1"
